# kitty.conf — Eva-01 x Gundam

# Shell padrao
shell /usr/bin/zsh

# Transparencia 65% opaco
background_opacity 0.65

# Bordas da janela — verde neon ativo, roxo apagado inativo
active_border_color #00af5f
inactive_border_color #5f5f87

# Ctrl+9 e Ctrl+0 -> envia ESC+9 e ESC+0 pro tmux (M-9 / M-0)
map ctrl+9 send_text all \x1b9
map ctrl+0 send_text all \x1b0