# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="eva01"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# fzf
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ]   && source /usr/share/doc/fzf/examples/completion.zsh

# ROS 2 Humble
source /opt/ros/humble/setup.zsh

# LASER aliases, funcoes e auto-tmux
source $HOME/.zshrc_laser_aliases